### ISSUE TITLE
No such file or directory: 'ivector-plda-scoring'

### ISSUE THREAD

**Issue by woliyanyan** [FAKEBOB-adversarial-attack/FAKEBOB#18]
hello！
when I run build_spk_models.py, I face the error: No such file or directory: 'ivector-plda-scoring'
But 'ivector-plda-scoring' exists in kaldi/src/ivectorbin.
![1](https://user-images.githubusercontent.com/73336858/145530781-17785a98-dd59-41ae-a965-338303c01e24.png)

I hope to get your  help.

**Comment by SEC4SR** [comment]
Could you run 'which ivector-plda-scoring' in your terminal and provide the output?
The possible reason is that you do not set up the environment properly so that the system cannot find it.
Did you follow the suggestion in step-6 in README ?

Step-6: Setting the System Variable which kaldi relies on. We have made it as simple as possible. You just need to copy and paste all the commands in path_cmd.sh to your ~/.zshrc or ~/.bashrc. Do not forget to modify KALDI_ROOT and FAKEBOB_PATH in path_cmd.sh

**Comment by GolferChen** [comment]
Could you run 'which ivector-plda-scoring' in your terminal and provide the output?
The possible reason is that you do not set up the environment properly so that the system cannot find it.
Did you follow the suggestion in step-6 in README ?

Step-6: Setting the System Variable which kaldi relies on. We have made it as simple as possible. You just need to copy and paste all the commands in path_cmd.sh to your ~/.zshrc or ~/.bashrc. Do not forget to modify KALDI_ROOT and FAKEBOB_PATH in path_cmd.sh

**Comment by GolferChen** [comment]
Notice: if your shell is bash, then you should paste the commands in path_cmd.sh to your ~/.bashrc, not ~/.zshrc, and `source ~/.bashrc`, not `source ~/.zshrc`.
Check the type of your shell by 'echo $0'

**Comment by woliyanyan** [comment]
It can be found and output in the terminal,
![2](https://user-images.githubusercontent.com/73336858/145568885-dfe3f3f2-cdf8-4a0d-9d67-81e6d044bcb9.png)

And set it according to the suggestions in step 6 of the readme。
But the problem remains unresolved

**Comment by FAKEBOB-adversarial-attack** [comment]
Quite weird...

Could you set `debug = True` in the line 36 of `build_spk_models.py`, re-run the file and provide the log?

**Comment by woliyanyan** [comment]
this is the running log after modifying debug = true
![1](https://user-images.githubusercontent.com/73336858/145579885-1ea11366-e09d-48b3-ba6a-9dcea5064a19.png)

**Comment by FAKEBOB-adversarial-attack** [comment]
I see.
So the problem may be not due to `ivector-plda-scoring` since your program even fails at the step of mfcc extraction.

As the first red-colored line of the log indicates, the system cannot find parse_options.sh. This script is in `pre-models/utils/` and `path_cmd.sh` in step-6  has appended it to the PATH environment variable.

Could you run `which parse_options.sh` and provide the output? This is my output.

<img width="429" alt="image" src="https://user-images.githubusercontent.com/57412561/145585064-aebdcf17-8086-4791-b895-b0a9b5518c18.png">

**Comment by woliyanyan** [comment]
This is my output.
![1](https://user-images.githubusercontent.com/73336858/145667747-2003cbb2-9e1f-4ef8-bd0f-bc1078f28a70.png)

**Comment by FAKEBOB-adversarial-attack** [comment]
What is your shell type? Zsh?

**Comment by woliyanyan** [comment]
![2](https://user-images.githubusercontent.com/73336858/145668072-e8a36577-f770-489d-ae43-34268839c607.png)

**Comment by FAKEBOB-adversarial-attack** [comment]
Quite confusing. Currently, I cannot figure out why the system can find all these files when you run `which xx`, but fail to find them when you run `build_spk_models.py`.

I will try to reproduce the manual installation from scratch on a new machine to see whether your problem is a common one.

Before that, I suggest you turn to docker installation. It will save you much effort.

**Comment by woliyanyan** [comment]
OK, thank you. Please!

**Comment by FAKEBOB-adversarial-attack** [comment]
Hi, I have reproduced the manual installation from scratch on a new machine (not the one I previously worked on). Everything went smoothly. The only exception is that I accidentally forgot to run `source ~/.zshrc` in step-6 and encountered the same problem as you. However, the problem was easily fixed after I executed `source ~/.zshrc`.

So did you strictly follow the instruction of manual installation (especially step-6)?
